baseURL = "https://kumpeishiraishi.github.io/"
title = "Kumpei Shiraishi"
theme = "minimal-bootstrap-hugo-theme"

[params]
  description = "Postdoc in physics"
  contentBackgroundColor = "#F4F5F7"
  contentTextColor = "#212529"
  contentLinkColor = "#007bff"
  contentLinkHoverColor = "#0056b3"
  navbarBackgroundColor = "#212529"
  navbarLinkColor = "rgba(255, 255, 255, 0.8)"
  navbarLinkHoverColor = "rgba(255, 255, 255, 1)"
  wrapperMaxWidth = "960px"
  customDateFormat = "Jan 2, 2006"
  customCodeStyle = true
  customBlockquoteStyle = true
  showPostSummary = false
  cookieConsent = false
  includeBootstrapJs = false
  faviconSafariPinnedTabColor = "#5bbad5"
  faviconMsApplicationTileColor = "#da532c"
  faviconThemeColor = "#ffffff"

[menu]
  [[menu.nav]]
  name = "Home"
  url = "/"
  weight = 1
  [[menu.nav]]
  name = "Publications"
  url = "/publications/"
  weight = 2
  [[menu.nav]]
  name = "Presentations"
  url = "/presentations/"
  weight = 3

#[markup]
#  defaultMarkdownHandler = "goldmark"
#  [markup.goldmark]
#    [markup.goldmark.extensions]
#      definitionList = true
#      footnote = true
#      linkify = true
#      strikethrough = true
#      table = true
#      taskList = true
#      typographer = true
#    [markup.goldmark.parser]
#      attribute = true
#      autoHeadingID = true
#    [markup.goldmark.renderer]
#      hardWraps = false
#      unsafe = true
#      xHTML = false
#  [markup.highlight]
#    codeFences = true
#    hl_Lines = ""
#    lineNoStart = 1
#    lineNos = false
#    lineNumbersInTable = true
#    noClasses = true
#    style = "monokai"
#    tabWidth = 4
#  [markup.tableOfContents]
#    endLevel = 6
#    startLevel = 2