baseURL = "https://kumpeishiraishi.github.io/"
title = "Kumpei Shiraishi"
theme = "hugo-theme-yue"

defaultContentLanguageInSubdir = false
enableGitInfo = false
enableEmoji = false
enableRobotsTXT = false

[params]
_merge = "deep"
images = [ "favicon.ico" ]
toc = false

[frontmatter]
lastmod = [ "lastmod", ":default" ]

[markup]
_merge = "deep"

[menus]
[[menus.main]]
name = "Home"
pageRef = "/"
weight = 10

[[menus.main]]
name = "Publications"
pageRef = "/publications"
weight = 20

[[menus.main]]
name = "Presentations"
pageRef = "/presentations"
weight = 30

[[menus.main]]
name = "Misc"
pageRef = "/misc"
weight = 40
